# AppVeyor CI build file

# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

# version format
version: 0.0.{build}
image: Visual Studio 2017

shallow_clone: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cmd: build.bat Package

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

# to disable automatic tests 
test: on

# skip building commits that add tags (such as release tag)
skip_tags: true

skip_commits:
  author: buildbot171
  files:
    - docs/*
    - README.md
    - LICENSE
    
#---------------------------------#
#       artifacts configuration   #
#---------------------------------#

nuget:
  disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to account/project feeds for pull request builds

artifacts:
  - path: '**\Advanced.Algorithms.*.nupkg'

environment:
  github_access_token:
    secure: mZLeq0GTB9kb5b6+HnVpJB6hhiYMJIQ2+Zf/DwZ/LEIyxJaYB1nx36aGHXE9q1cN
  github_email:
    secure: iBJZGqxyiHVNeYI0uIW+MdGd3I3pg8brJtETNRkKe/A=
  nuget_access_token:
    secure: JY57cW8JFacDy3vxpqbzcWdurADIal7t3DDeLlRyi2QXcH8lMTdmpizbEjiy1qt3
deploy:
- provider: GitHub
  auth_token: $(github_access_token)
  on:
    branch: /(stable|beta)/ 
- provider: NuGet
  api_key: $(nuget_access_token)
  on:
    branch: /(stable|beta)/
