<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Advanced.Algorithms</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>StrongNameKey.snk</AssemblyOriginatorKeyFile>
    <DelaySign>False</DelaySign>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <VersionPrefix>1.0.0.0</VersionPrefix>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Binary\**" />
    <Compile Remove="DynamicProgramming\**" />
    <EmbeddedResource Remove="Binary\**" />
    <EmbeddedResource Remove="DynamicProgramming\**" />
    <None Remove="Binary\**" />
    <None Remove="DynamicProgramming\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Binary\BaseConversion.cs" />
    <Compile Include="Binary\Logarithm.cs" />
    <Compile Include="Binary\GCD.cs" />
  </ItemGroup>
 
</Project>